### ISSUE TITLE
Middleware will terminal if it faces an exception.

### ISSUE THREAD

**Issue by lenguyenthanh** [pardom-zz/redux-observable#6]
I'm trying integrate redux-kotlin to our app. It works extreme well except when observable middleware. It will stop working if there is some exception are occurred.

How do you guy solve this issue? Thank you so much.

**Comment by AngusMorton** [comment]
This is, I imagine, expected behaviour.

You should use the error handling features of RxJava to catch this exception and ensure it doesn't propagate into the rest of the stream.

**Comment by lenguyenthanh** [comment]
Agree, It should work great `onErrorReturn` operation.
